"""empty message

Revision ID: 3c4bf8ac08e0
Revises: ef078c479061
Create Date: 2026-06-19 23:32:42.233153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c4bf8ac08e0'
down_revision: Union[str, Sequence[str], None] = 'ef078c479061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('travels', sa.Column('share_token', sa.String(length=36), nullable=True, comment='공개 공유 토큰 (UUID)'))
    op.create_index(op.f('ix_travels_share_token'), 'travels', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travels_share_token'), table_name='travels')
    op.drop_column('travels', 'share_token')
    # ### end Alembic commands ###
