"""empty message

Revision ID: 3ca74952934f
Revises: 
Create Date: 2026-06-21 02:42:22.056159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ca74952934f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_rooms',
    sa.Column('room_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_name', sa.String(length=100), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('member_ids', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('room_id')
    )
    op.create_table('travels',
    sa.Column('travel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='여행 제목'),
    sa.Column('destination', sa.String(length=100), nullable=False, comment='목적지 (예: 제주도, 파리)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='여행 시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='여행 종료일'),
    sa.Column('share_token', sa.String(length=36), nullable=True, comment='공개 공유 토큰 (UUID)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('travel_id')
    )
    op.create_index(op.f('ix_travels_owner_id'), 'travels', ['owner_id'], unique=False)
    op.create_index(op.f('ix_travels_share_token'), 'travels', ['share_token'], unique=True)
    op.create_table('chat_messages',
    sa.Column('message_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('message_type', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.create_index(op.f('ix_chat_messages_room_id'), 'chat_messages', ['room_id'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=False, comment='소속 여행 ID'),
    sa.Column('day_number', sa.Integer(), nullable=False, comment='몇 일차 (1-based)'),
    sa.Column('date', sa.Date(), nullable=False, comment='해당 일정 날짜'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='같은 날 내 방문 순서 (0-based)'),
    sa.Column('place_name', sa.String(length=100), nullable=False, comment='장소명'),
    sa.Column('place_address', sa.String(length=255), nullable=True, comment='주소'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='위도 (지도 뷰)'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='경도 (지도 뷰)'),
    sa.Column('category', sa.Enum('SIGHTSEEING', 'RESTAURANT', 'ACCOMMODATION', 'TRANSPORT', 'SHOPPING', 'ETC', name='schedulecategoryenum'), nullable=False, comment='장소 카테고리'),
    sa.Column('cost', sa.Integer(), nullable=True, comment='예상 비용 (원, 0=무료, None=미입력)'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='방문 시작 시각'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='방문 종료 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.travel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedules_travel_id'), 'schedules', ['travel_id'], unique=False)
    op.create_table('chat_room_members',
    sa.Column('member_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('last_read_message_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_read_message_id'], ['chat_messages.message_id'], ),
    sa.ForeignKeyConstraint(['room_id'], ['chat_rooms.room_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id')
    )
    op.create_index(op.f('ix_chat_room_members_room_id'), 'chat_room_members', ['room_id'], unique=False)
    op.create_index(op.f('ix_chat_room_members_user_id'), 'chat_room_members', ['user_id'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False, comment='소속 일정 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='메모 내용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_schedule_id'), 'memos', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memos_schedule_id'), table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_chat_room_members_user_id'), table_name='chat_room_members')
    op.drop_index(op.f('ix_chat_room_members_room_id'), table_name='chat_room_members')
    op.drop_table('chat_room_members')
    op.drop_index(op.f('ix_schedules_travel_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_chat_messages_room_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_travels_share_token'), table_name='travels')
    op.drop_index(op.f('ix_travels_owner_id'), table_name='travels')
    op.drop_table('travels')
    op.drop_table('chat_rooms')
    # ### end Alembic commands ###
