"""empty message

Revision ID: 4755d9eca068
Revises: 
Create Date: 2026-05-24 14:20:28.151768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import app

# revision identifiers, used by Alembic.
revision: str = '4755d9eca068'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('unique_id', sa.String(length=6), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('tags', app.models.user_model.JSONList(), nullable=False),
    sa.Column('auth_provider', sa.Enum('LOCAL', 'KAKAO', 'GOOGLE', name='authprovider', native_enum=False), nullable=False),
    sa.Column('social_id', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_unique_id'), 'users', ['unique_id'], unique=True)
    op.create_index(op.f('ix_users_user_id'), 'users', ['user_id'], unique=False)
    op.create_table('friendships',
    sa.Column('friendship_id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.Integer(), nullable=False),
    sa.Column('addressee_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'BLOCKED', name='friendshipstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('friendship_id')
    )
    op.create_index(op.f('ix_friendships_friendship_id'), 'friendships', ['friendship_id'], unique=False)
    op.create_table('travels',
    sa.Column('travel_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False, comment='여행 제목'),
    sa.Column('destination', sa.String(length=100), nullable=False, comment='목적지 (예: 제주도, 파리)'),
    sa.Column('start_date', sa.Date(), nullable=False, comment='여행 시작일'),
    sa.Column('end_date', sa.Date(), nullable=False, comment='여행 종료일'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('travel_id')
    )
    op.create_index(op.f('ix_travels_owner_id'), 'travels', ['owner_id'], unique=False)
    op.create_table('schedules',
    sa.Column('schedule_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('travel_id', sa.Integer(), nullable=False, comment='소속 여행 ID'),
    sa.Column('day_number', sa.Integer(), nullable=False, comment='몇 일차 (1-based)'),
    sa.Column('date', sa.Date(), nullable=False, comment='해당 일정 날짜'),
    sa.Column('order_index', sa.Integer(), nullable=False, comment='같은 날 내 방문 순서 (0-based)'),
    sa.Column('place_name', sa.String(length=100), nullable=False, comment='장소명'),
    sa.Column('place_address', sa.String(length=255), nullable=True, comment='주소'),
    sa.Column('latitude', sa.Float(), nullable=True, comment='위도 (지도 뷰)'),
    sa.Column('longitude', sa.Float(), nullable=True, comment='경도 (지도 뷰)'),
    sa.Column('category', sa.Enum('SIGHTSEEING', 'RESTAURANT', 'ACCOMMODATION', 'TRANSPORT', 'SHOPPING', 'ETC', name='schedulecategoryenum'), nullable=False, comment='장소 카테고리'),
    sa.Column('cost', sa.Integer(), nullable=True, comment='예상 비용 (원, 0=무료, None=미입력)'),
    sa.Column('start_time', sa.Time(), nullable=True, comment='방문 시작 시각'),
    sa.Column('end_time', sa.Time(), nullable=True, comment='방문 종료 시각'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['travel_id'], ['travels.travel_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('schedule_id')
    )
    op.create_index(op.f('ix_schedules_travel_id'), 'schedules', ['travel_id'], unique=False)
    op.create_table('memos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False, comment='소속 일정 ID'),
    sa.Column('content', sa.Text(), nullable=False, comment='메모 내용'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['schedules.schedule_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_memos_schedule_id'), 'memos', ['schedule_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memos_schedule_id'), table_name='memos')
    op.drop_table('memos')
    op.drop_index(op.f('ix_schedules_travel_id'), table_name='schedules')
    op.drop_table('schedules')
    op.drop_index(op.f('ix_travels_owner_id'), table_name='travels')
    op.drop_table('travels')
    op.drop_index(op.f('ix_friendships_friendship_id'), table_name='friendships')
    op.drop_table('friendships')
    op.drop_index(op.f('ix_users_user_id'), table_name='users')
    op.drop_index(op.f('ix_users_unique_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
