"""empty message

Revision ID: 5948fa9d3533
Revises: 9806ced48412
Create Date: 2026-07-22 13:45:21.295540

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5948fa9d3533'
down_revision: Union[str, Sequence[str], None] = '9806ced48412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image', sa.String(length=512), nullable=True))
    op.drop_column('users', 'profile_image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_image_url', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.drop_column('users', 'profile_image')
    # ### end Alembic commands ###
