"""empty message

Revision ID: ef078c479061
Revises: 4755d9eca068
Create Date: 2026-06-14 19:43:48.086727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ef078c479061'
down_revision: Union[str, Sequence[str], None] = '4755d9eca068'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status_message', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('profile_image_url', sa.String(length=512), nullable=True))
    op.add_column('users', sa.Column('avatar_color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_color')
    op.drop_column('users', 'profile_image_url')
    op.drop_column('users', 'status_message')
    # ### end Alembic commands ###
